module.exports = [
    { id: 1, name: 'bela', food:"pro plan", ownerFirstName: "Einat", ownerLastName: "Miller Joan" },
    { id: 2, name: 'chips', food:"pro plan", ownerFirstName: "Chen", ownerLastName: "Bahiri" },
    { id: 3, name: 'Effy', food:"pro plan", ownerFirstName: "Tal", ownerLastName: "Turgeman", description: "small, vibrant and hungry" },
    { id: 4, name: 'gever', food:"pro plan", ownerFirstName: "Hagar", ownerLastName: "Shtroitman", description: "very masculine" },
    { id: 5, name: 'jessa', food:"pro plan", ownerFirstName: "Dana", ownerLastName: "Richker", description: "always on guard but so gentle" },
    { id: 6, name: 'kaya_and_pippin', food:"pro plan", ownerFirstName: "Elad", ownerLastName: "Alon" },
    { id: 7, name: 'kepi', food:"pro plan", ownerFirstName: "Hany", ownerLastName: "Lynn", description: "a carpet"},
    { id: 8, name: 'lucy', food:"pro plan", ownerFirstName: "Shahar", ownerLastName: "Epstein", description: "loves her space" },
    { id: 9, name: 'luna', food:"pro plan", ownerFirstName: "Chen", ownerLastName: "Shusterman" },
    { id: 10, name: 'mushu', food:"pro plan", ownerFirstName: "Ofir", ownerLastName: "Machanian" },
    { id: 11, name: 'panda', food:"pro plan", ownerFirstName: "Chen", ownerLastName: "Ganon" },
    { id: 12, name: 'viva', food:"pro plan", ownerFirstName: "Srul", ownerLastName: "Pinkas", description: "the oldest puppy alive" },
    { id: 13, name: 'ziggyT', food:"pro plan", ownerFirstName: "Artyom", ownerLastName: "Tochilovsky" },
    { id: 14, name: 'ziggyY', food:"pro plan", ownerFirstName: "Nadav", ownerLastName: "Yaron" },
    { id: 15, name: 'bubbles', food:"pro plan", ownerFirstName: "Lena", ownerLastName: "Oks", description: "spoiled but beautiful" },
    { id: 16, name: 'nils', food:"pro plan", ownerFirstName: "Atar", ownerLastName: "Yihia", description: "vigilant but loving" },
    { id: 17, name: 'johnny', food:"pro plan", ownerFirstName: "Elad", ownerLastName: "Cohen", description: "sweet old boy" },
    { id: 18, name: 'peach', food:"pro plan", ownerFirstName: "Irit", ownerLastName: "Avidan", description: "Shy and adorable" },
];
