module.exports = [
    { id: 1, name: 'bela', owner: 'Einat Miller Joan', type: 'aaaa', food: 'bbb', alergies: '', description: 'A really cute dog' },
    { id: 2, name: 'chips', owner: 'Chen Bahiri', type: 'aaaa', food: 'bbb', alergies: '', description: 'A really cute dog' },
    { id: 3, name: 'Effy', owner: 'Tal Turgeman', type: 'aaaa', food: 'bbb', alergies: '', description: 'A really cute dog' },
    { id: 4, name: 'gever', owner: 'Hagar Shtroitman', type: 'aaaa', food: 'bbb', alergies: '', description: 'A really cute dog' },
    { id: 5, name: 'jessa', owner: 'Dana Richker', type: 'aaaa', food: 'bbb', alergies: '', description: 'A really cute dog' },
    { id: 6, name: 'kaya_and_pippin', owner: 'Elad Alon', type: 'aaaa', food: 'bbb', alergies: '', description: 'A really cute dog' },
    { id: 7, name: 'kepi', owner: 'Hany Lynn', type: 'aaaa', food: 'bbb', alergies: '', description: 'A really cute dog' },
    { id: 8, name: 'lucy', owner: 'Shahar Epstein', type: 'aaaa', food: 'bbb', alergies: '', description: 'A really cute dog' },
    { id: 9, name: 'luna', owner: 'Chen Shusterman', type: 'aaaa', food: 'bbb', alergies: '', description: 'A really cute dog' },
    { id: 10, name: 'mushu', owner: 'Ofir Machanian', type: 'aaaa', food: 'bbb', alergies: '', description: 'A really cute dog' },
    { id: 11, name: 'panda', owner: 'Chen Ganon', type: 'aaaa', food: 'bbb', alergies: '', description: 'A really cute dog' },
    { id: 12, name: 'viva', owner: 'Srul Pinkas', type: 'aaaa', food: 'bbb', alergies: '', description: 'A really cute dog' },
    { id: 13, name: 'ziggyT', owner: 'Artyom Tochilovsky', type: 'aaaa', food: 'bbb', alergies: '', description: 'A really cute dog' },
    { id: 14, name: 'ziggyY', owner: 'Nadav Yaron', type: 'aaaa', food: 'bbb', alergies: '', description: 'A really cute dog' },
    { id: 15, name: 'Bubbles', owner: 'Lena Oks', type: 'aaaa', food: 'bbb', alergies: '', description: 'A really cute dog' },
    { id: 16, name: 'anondog', owner: 'Atar Yihia', type: 'aaaa', food: 'bbb', alergies: '', description: 'A really cute dog' },
    { id: 17, name: 'johnny', owner: 'Elad Cohen', type: 'aaaa', food: 'bbb', alergies: '', description: 'A really cute dog' },
];
