module.exports = [
    { id: 1, name: 'Bela', owner: 'Einat Miller Joan', imgSrc:'/images/dogs/bela.jpg', food: 'pro plan', allergies: '', description: 'A really cute dog' },
    { id: 2, name: 'Chips', owner: 'Chen Bahiri', imgSrc:'/images/dogs/chips.jpg', food: 'pro plan', alergies: '', description: 'very sweet, loves to jump' },
    { id: 3, name: 'Effy', owner: 'Tal Turgeman', imgSrc:'/images/dogs/Effy.jpg', food: 'pro plan', alergies: '', description: 'small, vibrant and hungry' },
    { id: 4, name: 'Gever', owner: 'Hagar Shtroitman', imgSrc:'/images/dogs/gever.jpg', food: 'pro plan', alergies: '', description: 'very masculine' },
    { id: 5, name: 'Jessa', owner: 'Dana Richker', imgSrc:'/images/dogs/jessa.JPG', food: 'pro plan', alergies: '', description: 'always on guard but so gentle' },
    { id: 6, name: 'Kaya and Pippin', owner: 'Elad Alon', imgSrc:'/images/dogs/kaya_and_pippin.png', food: 'pro plan', alergies: '', description: 'best friends forever' },
    { id: 7, name: 'Kepi', owner: 'Hany Lynn', imgSrc:'/images/dogs/kepi.png', food: 'pro plan', alergies: '', description: 'a carpet' },
    { id: 8, name: 'Lucy', owner: 'Shahar Epstein', imgSrc:'/images/dogs/lucy.jpg', food: 'pro plan', alergies: '', description: 'loves her space' },
    { id: 9, name: 'Luna', owner: 'Chen Shusterman', imgSrc:'/images/dogs/luna.jpg', food: 'pro plan', alergies: '', description: 'A really cute dog' },
    { id: 10, name: 'Mushu', owner: 'Ofir Machanian', imgSrc:'/images/dogs/mushu.jpg', food: 'pro plan', alergies: '', description: 'A really cute dog' },
    { id: 11, name: 'Panda', owner: 'Chen Ganon', imgSrc:'/images/dogs/panda.jpg', food: 'pro plan', alergies: '', description: 'A really cute dog' },
    { id: 12, name: 'Viva', owner: 'Srul Pinkas', imgSrc:'/images/dogs/viva.png', food: 'pro plan', alergies: '', description: 'the oldest puppy alive' },
    { id: 13, name: 'ZiggyT', owner: 'Artyom Tochilovsky', imgSrc:'/images/dogs/ziggyT.jpg', food: 'pro plan', alergies: '', description: 'A really cute dog' },
    { id: 14, name: 'ZiggyY', owner: 'Nadav Yaron', imgSrc:'/images/dogs/ziggyY.jpg', food: 'pro plan', alergies: '', description: 'A really cute dog' },
    { id: 15, name: 'Bubbles', owner: 'Lena Oks', imgSrc:'/images/dogs/bubbles.jpg', food: 'pro plan', alergies: '', description: 'spoiled but beautiful' },
    { id: 16, name: 'Nils', owner: 'Atar Yihia', imgSrc:'/images/dogs/nils.jpg', food: 'pro plan', alergies: '', description: 'vigilant but loving' },
    { id: 17, name: 'Johnny', owner: 'Elad Cohen', imgSrc:'/images/dogs/johnny.jpg', food: 'pro plan', alergies: '', description: 'sweet old boy' },
    { id: 18, name: 'Peach', owner: 'Irit Avidan', imgSrc:'/images/dogs/peach.jpg', food: 'pro plan', alergies: '', description: 'shy and adorable' },
];
