module.exports = [
    { id: 1, firstName: "Einat", lastName: "Miller Joan", email: 'a@a.com', 'dogId': 1 },
    { id: 2, firstName: "Chen", lastName: "Bahiri", email: 'a@a.com', 'dogId': 2 },
    { id: 3, firstName: "Tal", lastName: "Turgeman", email: 'a@a.com', 'dogId': 3 },
    { id: 4, firstName: "Hagar", lastName: "Shtroitman", email: 'a@a.com', 'dogId': 4 },
    { id: 5, firstName: "Dana", lastName: "Richker", email: 'a@a.com', 'dogId': 5 },
    { id: 6, firstName: "Elad", lastName: "Alon", email: 'a@a.com', 'dogId': 6 },
    { id: 7, firstName: "Hany", lastName: "Lynn", email: 'a@a.com', 'dogId': 7 },
    { id: 8, firstName: "Shahar", lastName: "Epstein", email: 'a@a.com', 'dogId': 8 },
    { id: 9, firstName: "Chen", lastName: "Shusterman", email: 'a@a.com', 'dogId': 9 },
    { id: 10, firstName: "Ofir", lastName: "Machanian", email: 'a@a.com', 'dogId': 10 },
    { id: 11, firstName: "Chen", lastName: "Ganon", email: 'a@a.com', 'dogId': 11 },
    { id: 12, firstName: "Srul", lastName: "Pinkas", email: 'a@a.com', 'dogId': 12 },
    { id: 13, firstName: "Artyom", lastName: "Tochilovsky", email: 'a@a.com', 'dogId': 13 },
    { id: 14, firstName: "Nadav", lastName: "Yaron", email: 'a@a.com', 'dogId': 14 },
    { id: 15, firstName: "Lena", lastName: "Oks", email: 'a@a.com', 'dogId': 15 },
    { id: 16, firstName: "Atar", lastName: "Yihia", email: 'a@a.com', 'dogId': 16 },
    { id: 17, firstName: "Elad", lastName: "Cohen", email: 'a@a.com', 'dogId': 17 },
]
